{% set name = "itpminer" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5901bbee36f5970c31599ac6b9b4832c9d47e77cc710a838fd4eae0b2aae9049

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - networkx
    - pandas
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - itpminer
    - itpminer.utils
    - itpminer.utils.components

about:
  home: https://github.com/Local-E-Rewards-ML/itpminer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python implementation of ITPMiner algorithm
  doc_url: https://github.com/Local-E-Rewards-ML/itpminer
  dev_url: https://github.com/Local-E-Rewards-ML/itpminer

extra:
  recipe-maintainers:
    - chanyoungs
